version: "3"

services:
  main-container:
    hostname: main-container
    build:
      context: ./main-container
      dockerfile: ./Dockerfile
      args:
        - JAVA_HOME=$JAVA_HOME
        - HADOOP_HOME=$HADOOP_HOME
        - HIVE_HOME=$HIVE_HOME
        - TEZ_HOME=$TEZ_HOME
        - HBASE_HOME=$HBASE_HOME
        - USER_HOME=$USER_HOME
        - SPARK_HOME=$SPARK_HOME
        - LIVY_HOME=$LIVY_HOME
    tty: true
    env_file: .env
    ports:
      - 8998:8998 # Livy UI
  postgres95:
    hostname: postgres95
    image: postgres:9.5
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=hive
  catalogd:
    hostname: catalogd
    build:
      context: ./impala
      dockerfile: ./Dockerfile
      args:
        - IMPALA_HOME=$IMPALA_HOME
    env_file: .env
    command: >
      bash -c "
        source $IMPALA_HOME/bin/set-classpath.sh
        $IMPALA_HOME/be/build/latest/service/catalogd -log_dir=/opt/impala/logs -catalog_service_host=catalogd:26000 -state_store_host=statestored
      "
  statestored:
    hostname: statestored
    extends:
      service: catalogd
    command: >
      bash -c "
        source $IMPALA_HOME/bin/set-classpath.sh
        $IMPALA_HOME/be/build/latest/service/statestored -log_dir=/opt/impala/logs -state_store_port=24000 -state_store_host=statestored
      "
  impalad:
    hostname: impalad
    extends:
      service: catalogd
    command: >
      bash -c "
        source $IMPALA_HOME/bin/set-classpath.sh
        $IMPALA_HOME/be/build/latest/service/impalad -log_dir=/opt/impala/logs -state_store_port=24000 -state_store_host=statestored -catalog_service_host=catalogd -be_port=22000
      "
    restart: always
  nifi:
    hostname: nifi
    build:
      context: ./nifi
      dockerfile: ./Dockerfile
      args:
        - USER_HOME=$USER_HOME
        - NIFI_HOME=$NIFI_HOME
    env_file: .env
    environment:
      - NIFI_HOST=nifi
      - NIFI_WEB_PROXY_HOST=localhost:8080
    ports:
      - 8080:8443
    volumes:
      - ./volume/nifi:$NIFI_HOME
