version: "3"

services:
  main-container:
    build:
      context: ./main-container
      dockerfile: ./Dockerfile
      args:
        - JAVA_HOME=$JAVA_HOME
        - HADOOP_HOME=$HADOOP_HOME
        - HIVE_HOME=$HIVE_HOME
        - TEZ_HOME=$TEZ_HOME
        - HBASE_HOME=$HBASE_HOME
        - USER_HOME=$USER_HOME
        - SPARK_HOME=$SPARK_HOME
        - LIVY_HOME=$LIVY_HOME
    tty: true
    env_file: .env
    command: >
      bash -c "
        hdfs namenode -format
        service ssh start
        start-dfs.sh
        start-yarn.sh
        hdfs dfs -mkdir -p /user/root /tmp /user/hive/warehouse /apps/tez
        hdfs dfs -chmod g+w /tmp /user/hive/warehouse
        hdfs dfs -put $TEZ_HOME/share/tez.tar.gz /apps/tez
        $HIVE_HOME/bin/schematool -dbType postgres -initSchema
        hive --service metastore &
        $HBASE_HOME/bin/start-hbase.sh
        bash
      "
    hostname: main-container
    ports:
      - 8998:8998
  postgres95:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=hive
    hostname: postgres95
  catalogd:
    build:
      context: ./impala
      dockerfile: ./Dockerfile
      args:
        - IMPALA_HOME=$IMPALA_HOME
    env_file: .env
    hostname: catalogd
    command: >
      bash -c "
        source $IMPALA_HOME/bin/set-classpath.sh
        $IMPALA_HOME/be/build/latest/service/catalogd -log_dir=/opt/impala/logs -catalog_service_host=catalogd:26000 -state_store_host=statestored
      "
  statestored:
    extends:
      service: catalogd
    hostname: statestored
    command: >
      bash -c "
        source $IMPALA_HOME/bin/set-classpath.sh
        $IMPALA_HOME/be/build/latest/service/statestored -log_dir=/opt/impala/logs -state_store_port=24000 -state_store_host=statestored
      "
  impalad:
    extends:
      service: catalogd
    hostname: impalad
    restart: always
    command: >
      bash -c "
        source $IMPALA_HOME/bin/set-classpath.sh
        $IMPALA_HOME/be/build/latest/service/impalad -log_dir=/opt/impala/logs -state_store_port=24000 -state_store_host=statestored -catalog_service_host=catalogd -be_port=22000
      "
    ports:
      - 22000:22000
  nifi:
    hostname: nifi
    build:
      context: ./nifi
      dockerfile: ./Dockerfile
      args:
        - USER_HOME=$USER_HOME
        - NIFI_HOME=$NIFI_HOME
    environment:
      - NIFI_HOST=nifi
      - NIFI_WEB_PROXY_HOST=localhost:8080
    tty: true
    env_file: .env
    volumes:
      - ./volume/nifi:$NIFI_HOME
    ports:
      - 8080:8443
